# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_source', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_class', models.CharField(max_length=250)),
                ('box', models.CharField(max_length=1000)),
                ('img_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Image')),
            ],
        ),
    ]
