# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='img_id',
            new_name='img',
        ),
    ]
