# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0002_auto_20170712_0320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img_source',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='label',
            old_name='img_class',
            new_name='category',
        ),
    ]
