# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0003_auto_20170712_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.RenameField(
            model_name='label',
            old_name='box',
            new_name='position',
        ),
        migrations.AlterField(
            model_name='label',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Category'),
        ),
        migrations.AddField(
            model_name='attributes',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Category'),
        ),
        migrations.AddField(
            model_name='label',
            name='attribute',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='annotator.Attributes'),
            preserve_default=False,
        ),
    ]
