# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0004_auto_20170712_1245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attributes',
            new_name='Attribute',
        ),
    ]
