# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0005_auto_20170712_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='attribute',
            new_name='name',
        ),
        migrations.AddField(
            model_name='attribute',
            name='value',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
