# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0006_auto_20170712_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
